import { ErrorType, FieldTypes, FormField } from '../models/util.model';

export const ProposalContainerLabels: { [key: string]: FormField } = {
  salesRep: {
    fieldLabel: 'Sales Rep',
    fieldName: 'Sales_Rep',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'value' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Sales Rep is required.',
      },
    ],
  },
  leadGenerator: {
    fieldLabel: 'Lead Generator',
    fieldName: 'Lead_Generator',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.LABEL,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [],
  },
};
export const HomeOwnerLabels: { [key: string]: FormField } = {
  firstName: {
    fieldLabel: 'First Name',
    fieldName: 'First_Name',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'First Name is required.',
      },
    ],
  },
  lastName: {
    fieldLabel: 'Last Name',
    fieldName: 'Last_Name',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Last Name is required.',
      },
    ],
  },
  email: {
    fieldLabel: 'Email',
    fieldName: 'Email',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.EMAIL,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Email is required.',
      },
    ],
  },
  phone: {
    fieldLabel: 'Phone',
    fieldName: 'Phone',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.NUMBER,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Phone is required.',
      },
    ],
  },
  address: {
    fieldLabel: 'Address',
    fieldName: 'Address',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.AUTOSEARCH,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Address is required.',
      },
    ],
  },
  street1: {
    fieldLabel: '',
    fieldName: 'Street1',
    placeholder: 'Street1',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Street1 is required.',
      },
    ],
  },
  street2: {
    fieldLabel: '',
    fieldName: 'Street2',
    placeholder: 'Street2',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Street2 is required.',
      },
    ],
  },
  city: {
    fieldLabel: '',
    fieldName: 'City',
    placeholder: 'City',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'City is required.',
      },
    ],
  },
  state: {
    fieldLabel: '',
    fieldName: 'State',
    placeholder: 'State',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'value' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'State is required.',
      },
    ],
  },
  postalCode: {
    fieldLabel: '',
    fieldName: 'Postal_Code',
    placeholder: 'Postal Code',
    associatedfieldName: '',
    fieldType: FieldTypes.NUMBER,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Postal Code is required.',
      },
    ],
  },
  addCoSigner: {
    fieldLabel: 'Add Co-Signer',
    fieldName: 'Add_Co_Signer',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.CHECKBOX,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Add Co-Signer is required.',
      },
    ],
  },
  coSignerFirstName: {
    fieldLabel: 'First Name',
    fieldName: 'Co_Signer_First_Name',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'First Name is required.',
      },
    ],
  },
  coSignerLastName: {
    fieldLabel: 'Last Name',
    fieldName: 'Co_Signer_Last_Name',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Last Name is required.',
      },
    ],
  },
  coSignerEmail: {
    fieldLabel: 'Email',
    fieldName: 'Co_Signer_Email',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.EMAIL,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Email is required.',
      },
    ],
  },
  coSignerPhone: {
    fieldLabel: 'Phone',
    fieldName: 'Co_Signer_Phone',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.NUMBER,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Phone is required.',
      },
    ],
  },
};
