import { ErrorType, FieldTypes, FormField } from '../models/util.model';

export const ProposalContainerLabels: { [key: string]: FormField } = {
  salesRep: {
    fieldLabel: 'Sales Rep',
    fieldName: 'sales_rep',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'value' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Sales Rep is required.',
      },
    ],
  },
  leadGenerator: {
    fieldLabel: 'Lead Generator',
    fieldName: 'master_lead_owner',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.LABEL,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [],
  },
  mentor: {
    fieldLabel: 'Mentor',
    fieldName: 'mentor',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'value' },
    errors: [],
  },
};
export const HomeOwnerLabels: { [key: string]: FormField } = {
  firstName: {
    fieldLabel: 'First Name',
    fieldName: 'first_name',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'First Name is required.',
      },
    ],
  },
  lastName: {
    fieldLabel: 'Last Name',
    fieldName: 'last_name',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Last Name is required.',
      },
    ],
  },
  email: {
    fieldLabel: 'Email',
    fieldName: 'email',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.EMAIL,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Email is required.',
      },
    ],
  },
  phone: {
    fieldLabel: 'Phone',
    fieldName: 'phone',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Phone is required.',
      },
    ],
  },
  // address: {
  //   fieldLabel: 'Address',
  //   fieldName: 'address',
  //   placeholder: '',
  //   associatedfieldName: '',
  //   fieldType: FieldTypes.AUTOSEARCH,
  //   isEditable: true,
  //   isRequired: true,
  //   isDisabled: false,
  //   options: [],
  //   optionConfig: { labelKey: '', valueKey: '' },
  //   errors: [
  //     {
  //       type: ErrorType.REQUIRED,
  //       message: 'Address is required.',
  //     },
  //   ],
  // },
  address: {
    fieldLabel: 'Address',
    fieldName: 'address',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Address is required.',
      },
    ],
  },
  street1: {
    fieldLabel: '',
    fieldName: 'street',
    placeholder: 'Street1',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Street1 is required.',
      },
    ],
  },
  street2: {
    fieldLabel: '',
    fieldName: 'street_2',
    placeholder: 'Street2',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Street2 is required.',
      },
    ],
  },
  city: {
    fieldLabel: '',
    fieldName: 'city',
    placeholder: 'City',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'City is required.',
      },
    ],
  },
  state: {
    fieldLabel: '',
    fieldName: 'state',
    placeholder: 'State',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'value' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'State is required.',
      },
    ],
  },
  postalCode: {
    fieldLabel: '',
    fieldName: 'zip_code',
    placeholder: 'Postal Code',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Postal Code is required.',
      },
    ],
  },
  addCoSigner: {
    fieldLabel: 'Add Co-Signer',
    fieldName: 'Add_Co_Signer',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.CHECKBOX,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Add Co-Signer is required.',
      },
    ],
  },
  coSignerFirstName: {
    fieldLabel: 'First Name',
    fieldName: 'Co_Signer_First_Name',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'First Name is required.',
      },
    ],
  },
  coSignerLastName: {
    fieldLabel: 'Last Name',
    fieldName: 'Co_Signer_Last_Name',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Last Name is required.',
      },
    ],
  },
  coSignerEmail: {
    fieldLabel: 'Email',
    fieldName: 'Co_Signer_Email',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.EMAIL,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Email is required.',
      },
    ],
  },
  coSignerPhone: {
    fieldLabel: 'Phone',
    fieldName: 'Co_Signer_Phone',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.NUMBER,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Phone is required.',
      },
    ],
  },
};
export const UtilityLabels: { [key: string]: FormField } = {
  utility: {
    fieldLabel: 'Utility',
    fieldName: 'utility',
    placeholder: 'utility',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'value' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Utility is required.',
      },
    ],
  },
  accountOwner: {
    fieldLabel: 'Utility Account Owner Same As Homeowner',
    fieldName: 'accountOwner',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.CHECKBOX,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
    ],
  },
  firstName: {
    fieldLabel: 'First Name',
    fieldName: 'acntOwnerFrstName',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'First Name is required.',
      },
    ],
  },
  lastName: {
    fieldLabel: 'Last Name',
    fieldName: 'acntOwnerLastName',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Last Name is required.',
      },
    ],
  },
  email: {
    fieldLabel: 'Email',
    fieldName: 'acntOwnerEmail',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.EMAIL,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Email is required.',
      },
    ],
  },
  annualBill: {
    fieldLabel: 'Annual Bill ($)',
    fieldName: 'annual_bill',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'This Field is required.',
      },
    ],
  },
  annualKwh: {
    fieldLabel: 'Annual kWh',
    fieldName: 'annual_usage',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: '', valueKey: '' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'This Field is required.',
      },
    ],
  }
};

export const SolarLabels: { [key: string]: FormField } = {
  proposalType: {
    fieldLabel: 'Type',
    fieldName: 'proposal_type',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'value', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Type is required.',
      },
    ],
  },
  installer: {
    fieldLabel: 'Installer',
    fieldName: 'installer',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'value', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Installer is required.',
      },
    ],
  },
  panel: {
    fieldLabel: 'Panel',
    fieldName: 'panel',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'value' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Products panel is required.',
      },
    ],
  },
  inverter: {
    fieldLabel: 'Inverter',
    fieldName: 'inverter',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'value' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Products inverter is required.',
      },
    ],
  },
 
  roofType: {
    fieldLabel: 'Type',
    fieldName: 'roof_type',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'value' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Roof type is required.',
      },
    ],
  },
  homeType: {
    fieldLabel: 'Home Type',
    fieldName: 'home_type',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'value', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Home type is required.',
      },
    ],
  },
  panels: {
    fieldLabel: '# of Panels',
    fieldName: 'panels',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'value', valueKey: 'value' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'This field is required.',
      },
    ],
  },
}
