import {
  ErrorType,
  FieldTypes,
  FilterCondition,
  FilterType,
  FormField,
  ModuleRef,
  RoutingStep,
} from '../models/util.model';

const reportTypeArr: { id: string; name: string; checked: boolean }[] = [
  { name: 'Tabular Report', id: 'tabularReport', checked: true },
  { name: 'Summary Report', id: 'summaryReport', checked: false },
  { name: 'Matrix Report', id: 'matrixReport', checked: false },
];
export const ReportModuleLabels: { [key: string]: FormField } = {
  selectModule: {
    fieldLabel: '',
    fieldName: 'selectModule',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a Module.',
      },
    ],
  },
  reportType: {
    fieldLabel: '',
    fieldName: 'reportType',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.RADIO,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: reportTypeArr,
    optionConfig: { labelKey: 'name', valueKey: 'id', checkedKey: 'checked' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a Report Type.',
      },
    ],
  },
};

export const ModuleData: ModuleRef[] = [
  {
    id: 'Contacts',
    name: 'Contacts',
    label: 'Contact',
    columns: [
      {
        id: '2nd Marketer',
        name: '2nd Marketer',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Average Bill',
        name: 'Average Bill(Contact)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Average Time Spent(Minutes)',
        name: 'Average Time Spent(Minutes)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Contact Owner',
        name: 'Contact Owner',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Created By(Contact)',
        name: 'Created By(Contact)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Created Time(Contact)',
        name: 'Created Time(Contact)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Date Created',
        name: 'Date Created',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Date/Time Schedule',
        name: 'Date/Time Schedule',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Days Visited',
        name: 'Days Visited',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Description(Contact)',
        name: 'Description(Contact)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Email',
        name: 'Email',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Emergency Consultant',
        name: 'Emergency Consultant',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'First Name',
        name: 'First Name',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'First Page Visited',
        name: 'First Page Visited',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'First Visit',
        name: 'First Visit',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Freedom ID',
        name: 'Freedom ID',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Full Name',
        name: 'Full Name',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Home Sq Ft',
        name: 'Home Sq Ft',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Last Activity Time(Contact)',
        name: 'Last Activity Time(Contact)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Last Name',
        name: 'Last Name',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Lead Source',
        name: 'Lead Source',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'LeadIdCPY',
        name: 'LeadIdCPY',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Mailing City',
        name: 'Mailing City',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Mailing State',
        name: 'Mailing State',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Mailing Street',
        name: 'Mailing Street',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Mailing Zip',
        name: 'Mailing Zip',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Marketer',
        name: 'Marketer',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Modified By(Contact)',
        name: 'Modified By(Contact)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Modified Time(Contact)',
        name: 'Modified Time(Contact)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Most Recent Visit',
        name: 'Most Recent Visit',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Number Of Chats',
        name: 'Number Of Chats',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Phone(Contact)',
        name: 'Phone(Contact)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Qualified By',
        name: 'Qualified By',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Referrer',
        name: 'Referrer',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Salutation',
        name: 'Salutation',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Spouse Name',
        name: 'Spouse Name',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Tag(Contact)',
        name: 'Tag(Contact)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Unsubscribed Mode',
        name: 'Unsubscribed Mode',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Unsubscribed Time',
        name: 'Unsubscribed Time',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Visitor Score',
        name: 'Visitor Score',
        active: false,
        filterType: FilterType.ADVANCE,
      },
    ],
  },
  {
    id: 'Accounts',
    name: 'Accounts',
    label: 'Account',
    columns: [
      {
        id: 'Account_Name',
        name: 'Account Name',
        active: false,
        selected: true,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Account_Number',
        name: 'Account Number',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Account_Owner',
        name: 'Account Owner',
        active: false,
        selected: true,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Account_Site',
        name: 'Account Site',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Account_Type',
        name: 'Account Type',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Annual_Revenue',
        name: 'Annual Revenue',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Average_Bill',
        name: 'Average Bill',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Bill_City',
        name: 'Bill City',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Bill_Code',
        name: 'Bill Code',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Bill_Country',
        name: 'Bill Country',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Bill_State',
        name: 'Bill State',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Bill_Street',
        name: 'Bill Street',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Created_By',
        name: 'Created By',
        active: false,
        selected: true,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Created_Time',
        name: 'Created Time',
        active: false,
        filterType: FilterType.STANDARD,
      },
      {
        id: 'Description',
        name: 'Description',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Employees',
        name: 'Employees',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Fax',
        name: 'Fax',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Industry',
        name: 'Industry',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Last_Activity_Time',
        name: 'Last Activity Time',
        active: false,
        filterType: FilterType.STANDARD,
      },
      {
        id: 'Modified_By',
        name: 'Modified By',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Modified_Time',
        name: 'Modified Time',
        active: false,
        filterType: FilterType.STANDARD,
      },
      {
        id: 'Ownership',
        name: 'Ownership',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Parent_Account',
        name: 'Parent Account',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Phone',
        name: 'Phone',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Rating',
        name: 'Rating',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Reschedule_Cycle_Time',
        name: 'Reschedule Cycle Time',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Shipping_City',
        name: 'Shipping City',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Shipping_Code',
        name: 'Shipping Code',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Shipping_Country',
        name: 'Shipping Country',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Shipping_State',
        name: 'Shipping State',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Shipping_Street',
        name: 'Shipping Street',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'SIC_Code',
        name: 'SIC Code',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Tag',
        name: 'Tag',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Ticker_Symbol',
        name: 'Ticker Symbol',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Website',
        name: 'Website',
        active: false,
        filterType: FilterType.ADVANCE,
      },
    ],
  },
  {
    id: 'Deals',
    name: 'Deals',
    label: 'Deal',
    columns: [],
  },
  {
    id: 'Notes',
    name: 'Notes',
    label: '',
    columns: [
      {
        id: 'Created By(Note)',
        name: 'Created By(Note)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Created Time(Note)',
        name: 'Created Time(Note)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Modified By(Note)',
        name: 'Modified By(Note)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Modified Time(Note)',
        name: 'Modified Time(Note)',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Note Content',
        name: 'Note Content',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Note Owner',
        name: 'Note Owner',
        active: false,
        filterType: FilterType.ADVANCE,
      },
      {
        id: 'Note Title',
        name: 'Note Title',
        active: false,
        filterType: FilterType.ADVANCE,
      },
    ],
  },
  {
    id: 'Emails',
    name: 'Emails',
    label: '',
    columns: [],
  },
  {
    id: 'Users',
    name: 'Users',
    label: 'User',
    columns: [],
  },
];

export const RoutingStepsData: RoutingStep[] = [
  {
    stepId: 'moduleInfo',
    stepName: 'Module Information',
    isVisible: true,
  },
  {
    stepId: 'reportType',
    stepName: 'Report Type',
    isVisible: false,
  },
  {
    stepId: 'reportRepresentation',
    stepName: 'Report Representation',
    isVisible: false,
  },
  {
    stepId: 'reportFilter',
    stepName: 'Report Filter',
    isVisible: false,
  },

  {
    stepId: 'basicInfo',
    stepName: 'Basic Information',
    isVisible: false,
  },
];

export const BasicInfoFieldLabel: { [key: string]: FormField } = {
  selectFolder: {
    fieldLabel: '',
    fieldName: 'selectFolder',
    placeholder: 'Select Folder',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'FOLDER_NAME', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Select Folder is required.',
      },
    ],
  },
  reportName: {
    fieldLabel: '',
    fieldName: 'reportName',
    placeholder: 'Name',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Name is required.',
      },
    ],
  },
  description: {
    fieldLabel: '',
    fieldName: 'description',
    placeholder: 'Description',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXTAREA,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Description is required.',
      },
    ],
  },
};

const viewTypes: { id: string; name: string; checked: boolean }[] = [
  {
    id: 'onlyMe',
    name: 'Only me',
    checked: false,
  },
  {
    id: 'everyone',
    name: 'Everyone',
    checked: false,
  },
  {
    id: 'selectedUser',
    name: 'Selected users',
    checked: false,
  },
];
export const ReportFolderLabel: { [key: string]: FormField } = {
  folderName: {
    fieldLabel: 'Folder Name',
    fieldName: 'folder_name',
    placeholder: 'Folder Name',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Folder Name is required.',
      },
    ],
  },
  viewType: {
    fieldLabel: 'View Type',
    fieldName: 'viewType',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.RADIO,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: viewTypes,
    optionConfig: { labelKey: 'name', valueKey: 'id', checkedKey: 'checked' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a View Type.',
      },
    ],
  },
  selectedGroups: {
    fieldLabel: 'Groups',
    fieldName: 'view_by_group',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.RADIO,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: viewTypes,
    optionConfig: { labelKey: 'value', valueKey: 'id', checkedKey: 'checked' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a Groups.',
      },
    ],
  },
  selectedUsers: {
    fieldLabel: 'Users',
    fieldName: 'view_by_user',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.RADIO,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: viewTypes,
    optionConfig: {
      labelKey: 'name',
      valueKey: 'login_id',
      checkedKey: 'checked',
    },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a Users.',
      },
    ],
  },
  selectedRoles: {
    fieldLabel: 'Roles',
    fieldName: 'view_by_role',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.RADIO,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: viewTypes,
    optionConfig: { labelKey: 'value', valueKey: 'id', checkedKey: 'checked' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a Roles.',
      },
    ],
  },
};
export const ColumnDefsConfigs = [
  {
    headerName: 'Report Name',
    field: 'Account_Name',
  },
  {
    headerName: 'Description',
    field: 'Description',
  },
  {
    headerName: 'Last Run Date',
    field: 'Created_Time',
  },
];
export const FilterConditionsOptions: FilterCondition[] = [
  { id: 'custom', name: 'Custom' },
  { id: 'previousFY', name: 'Previous FY' },
  { id: 'currentFY', name: 'Current FY' },
  { id: 'nextFY', name: 'Next FY' },
  { id: 'today', name: 'Today' },
  { id: 'yesterday', name: 'Yesterday' },
  { id: 'tomorrow', name: 'Tomorrow' },
];
export const ReportFilterLabels: { [key: string]: FormField } = {
  standardFilterSelect: {
    fieldLabel: '',
    fieldName: 'standardFilterSelect',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a Value.',
      },
    ],
  },
  standardFilterCondition: {
    fieldLabel: '',
    fieldName: 'standardFilterCondition',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a Value.',
      },
    ],
  },
  startDate: {
    fieldLabel: '',
    fieldName: 'startDate',
    placeholder: 'Start Date',
    associatedfieldName: '',
    fieldType: FieldTypes.DATE,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Start Date can not be left blank.',
      },
    ],
  },
  endDate: {
    fieldLabel: '',
    fieldName: 'endDate',
    placeholder: 'End Date',
    associatedfieldName: '',
    fieldType: FieldTypes.DATE,
    isEditable: true,
    isRequired: true,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'End Date can not be left blank.',
      },
    ],
  },
  advanceFilterSelect: {
    fieldLabel: '',
    fieldName: 'advanceFilterSelect',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a Value.',
      },
    ],
  },
  advancedFilterCondition: {
    fieldLabel: '',
    fieldName: 'advancedFilterCondition',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.SELECT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a Value.',
      },
    ],
  },
  advancedFilterValue: {
    fieldLabel: '',
    fieldName: 'advancedFilterValue',
    placeholder: '',
    associatedfieldName: '',
    fieldType: FieldTypes.TEXT,
    isEditable: true,
    isRequired: false,
    isDisabled: false,
    options: [],
    optionConfig: { labelKey: 'name', valueKey: 'id' },
    errors: [
      {
        type: ErrorType.REQUIRED,
        message: 'Please select a Value.',
      },
    ],
  },
};
